package vista;

import java.util.List;
import entidades.*;
import helpers.ColumnItem;
import java.util.Arrays;
import javax.swing.JOptionPane;
import servicios.*;

/**
 *
 * @author Juan Antonio Soto Cabrera <https://github.com/jsotoca/>
 */
public class ListadoMedicamentosView extends javax.swing.JInternalFrame {

    private List<Medicamento> medicamentos;
    private List<Componente> componentes;
    private DataTableModel medicamentoModel, componenteModel;
    private List<ColumnItem> medicamentocolumnItems, componentescolumnItems;
    Componente actual = null;
    private static ListadoMedicamentosView instance;
    
    /**
     * Creates new form ListadoMedicamentosView
     */
    private ListadoMedicamentosView() {
        initModels();
        initComponents();
        listarMedicamentos();
        this.btnQuitar.setEnabled(false);
    }
    
    public static ListadoMedicamentosView getInstance() {
        if(instance == null) instance = new ListadoMedicamentosView();
        return instance;
    }
    
    private void initModels(){
        initMedicamentoModel();
        initComponenteModel();
    }
    
    private void initMedicamentoModel(){
        medicamentocolumnItems = Arrays.asList(
            new ColumnItem("codigo",String.class),
            new ColumnItem("nombre",String.class),
            new ColumnItem("precio",String.class),
            new ColumnItem("vigente",Boolean.class)
        );
        
        medicamentoModel = new DataTableModel(medicamentocolumnItems);
    }
    
    private void initComponenteModel(){
        componentescolumnItems = Arrays.asList(
            new ColumnItem("codigo",String.class),
            new ColumnItem("principio",String.class),
            new ColumnItem("concentracion",String.class),
            new ColumnItem("vigente",Boolean.class)
        );
        
        componenteModel = new DataTableModel(componentescolumnItems);
    }
    
    private void listarMedicamentos() {
        try{
            medicamentos = MedicamentoServicio.listarMedicamentosActivos();
            medicamentoModel.setValues(medicamentos);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se pudo listar los medicamentos");
        }
    }
    
    private void listarComponentes(int id_medicamento) {
        try{
            componenteModel.setValues(null);
            componentes = MedicamentoServicio.buscarComponentesPorMedicamento(id_medicamento);
            
            if (componentes.size() > 0) componenteModel.setValues(componentes);
            else {
                this.btnQuitar.setEnabled(false);
                JOptionPane.showMessageDialog(this, "No se encontraron componentes del medicamento seleccionado");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se pudo listar los componente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMedicamentos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbComponentes = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de medicamentos"));

        tbMedicamentos.setModel(this.medicamentoModel);
        tbMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedicamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMedicamentos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Composición del medicamento"));

        tbComponentes.setModel(this.componenteModel);
        tbComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarComponente(evt);
            }
        });
        jScrollPane2.setViewportView(tbComponentes);

        btnQuitar.setText("Quitar componente seleccionado");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnQuitar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnQuitar)
                .addContainerGap())
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedicamentosMouseClicked
        listarComponentes((int) tbMedicamentos.getValueAt(tbMedicamentos.getSelectedRow(), 0));
    }//GEN-LAST:event_tbMedicamentosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int filaComponente = this.tbComponentes.getSelectedRow();
        int filaMedicamento = this.tbMedicamentos.getSelectedRow();
        if( filaMedicamento> -1 && filaComponente > -1){
            int cod_med = (int) tbMedicamentos.getValueAt(filaMedicamento, 0);
            int cod_pri = (int) tbComponentes.getValueAt(filaComponente, 0);

            int dialogResult = JOptionPane.showConfirmDialog (this, "¿Estas seguro de eliminar este componente?");
            if(dialogResult == JOptionPane.YES_OPTION){
                this.actual = this.componentes.get(filaComponente);
                Medicamento med = new Medicamento();
                med.setCodigo(cod_med);
                PrincipioActivo pri = new  PrincipioActivo();
                pri.setCodigo(cod_pri);
                this.actual.setMedicamento(med);
                this.actual.setPrincipioActivo(pri);
                try {
                    ComponenteServicio.eliminarComponente(actual);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el componente");
                }
                this.actual = null;
                this.listarComponentes(cod_med);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un componente");
        }
        this.btnQuitar.setEnabled(false);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void seleccionarComponente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarComponente
        this.btnQuitar.setEnabled(true);
    }//GEN-LAST:event_seleccionarComponente


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbComponentes;
    private javax.swing.JTable tbMedicamentos;
    // End of variables declaration//GEN-END:variables
}
