

package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Juan Antonio Soto Cabrera <https://github.com/jsotoca/>
 */
public class PrincipalView extends javax.swing.JFrame {

    /** Creates new form PrincipalView */
    public PrincipalView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        meLaboratorios = new javax.swing.JMenuItem();
        meMedicamentos = new javax.swing.JMenuItem();
        mePrincipios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meListadoMedicamento = new javax.swing.JMenuItem();
        meBusquedaMedicamentosIguales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1059, Short.MAX_VALUE)
        );

        jMenu1.setText("Gestión");

        meLaboratorios.setText("Labotatorios");
        meLaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meLaboratoriosActionPerformed(evt);
            }
        });
        jMenu1.add(meLaboratorios);

        meMedicamentos.setText("Medicamentos");
        meMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meMedicamentosActionPerformed(evt);
            }
        });
        jMenu1.add(meMedicamentos);

        mePrincipios.setText("Principios Activos");
        mePrincipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mePrincipiosActionPerformed(evt);
            }
        });
        jMenu1.add(mePrincipios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        meListadoMedicamento.setText("Listado de medicamentos");
        meListadoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meListadoMedicamentoActionPerformed(evt);
            }
        });
        jMenu2.add(meListadoMedicamento);

        meBusquedaMedicamentosIguales.setText("Búsqueda de medicamentos iguales");
        jMenu2.add(meBusquedaMedicamentosIguales);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meLaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meLaboratoriosActionPerformed
        try {
            LaboratorioView lab = LaboratorioView.getInstance();
            panelContenedor.add(lab);
            lab.setLocation((panelContenedor.getWidth()-lab.getWidth())/2, (panelContenedor.getHeight()-lab.getHeight())/2);
            lab.show();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede abrir la ventana de labotatorios");
        }
    }//GEN-LAST:event_meLaboratoriosActionPerformed

    private void meMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meMedicamentosActionPerformed
        try {
            MedicamentoView med = MedicamentoView.getInstance();
            panelContenedor.add(med);
            med.setLocation((panelContenedor.getWidth()-med.getWidth())/2, (panelContenedor.getHeight()-med.getHeight())/2);
            med.show();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede abrir la ventana de medicamentos");
        }
    }//GEN-LAST:event_meMedicamentosActionPerformed

    private void mePrincipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mePrincipiosActionPerformed
        try {
            PrincipioActivoView prin = PrincipioActivoView.getInstance();
            panelContenedor.add(prin);
            prin.setLocation((panelContenedor.getWidth()-prin.getWidth())/2, (panelContenedor.getHeight()-prin.getHeight())/2);
            prin.show();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede abrir la ventana de principios activos");
        }
    }//GEN-LAST:event_mePrincipiosActionPerformed

    private void meListadoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meListadoMedicamentoActionPerformed
        try {
            ListadoMedicamentosView lis = ListadoMedicamentosView.getInstance();
            panelContenedor.add(lis);
            lis.setLocation((panelContenedor.getWidth()-lis.getWidth())/2, (panelContenedor.getHeight()-lis.getHeight())/2);
            lis.show();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede abrir la ventana de listado de medicaments");
        }
    }//GEN-LAST:event_meListadoMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meBusquedaMedicamentosIguales;
    private javax.swing.JMenuItem meLaboratorios;
    private javax.swing.JMenuItem meListadoMedicamento;
    private javax.swing.JMenuItem meMedicamentos;
    private javax.swing.JMenuItem mePrincipios;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

}
