package vista;

import entidades.PrincipioActivo;
import helpers.ColumnItem;
import java.awt.Component;
import java.awt.Dimension;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import servicios.PrincipioActivoServicio;

/**
 *
 * @author Juan Antonio Soto Cabrera <https://github.com/jsotoca/>
 */
public class PrincipioActivoView extends javax.swing.JInternalFrame {
    
    private List<PrincipioActivo> principios;
    private List<ColumnItem> columnItems;
    private DataTableModel principiosModel;
    private PrincipioActivo principioActivo;
    private boolean bandera;
    
    private static PrincipioActivoView instance;

    /**
     * Creates new form PrincipioActivoView
     */
    private PrincipioActivoView() {
        initModel();
        
        Dimension screenSize = new Dimension(850, 560);
        setPreferredSize(screenSize);
        
        initComponents();
        
        setPanelEnabled(panDataPrin,false);
        
        listarPrincipiosActivos();
    }
    
    public static PrincipioActivoView getInstance() {
        if(instance == null) instance = new PrincipioActivoView();
        return instance;
    }
    
    private void initModel(){
        columnItems = Arrays.asList(
            new ColumnItem("codigo",String.class),
            new ColumnItem("nombre",String.class),
            new ColumnItem("descripcion",String.class),
            new ColumnItem("vigente",Boolean.class)
        );
        
        principiosModel = new DataTableModel(columnItems);
    }
    
    private void setPanelEnabled(JPanel panel, Boolean isEnabled) {
        panel.setEnabled(isEnabled);

            Component[] components = panel.getComponents();

        for (Component component : components) {
            if ("javax.swing.JPanel".equals(component.getClass().getName())) {
                setPanelEnabled((JPanel) component, isEnabled);
            }
            component.setEnabled(isEnabled);
        }
    }
    
    private void listarPrincipiosActivos() {
        try{
            this.principios = PrincipioActivoServicio.listarPrincipioActivos();
            this.principiosModel.setValues(this.principios);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se pudo listar los laboratorios");
        }
    }
    
    private void limpiarDatos(){
        txtNombrePrin.setText("");
        txtNombrePrin.requestFocus();
        txtDescripcionPrin.setText("");
        cbVigenciaPrin.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDataPrin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombrePrin = new javax.swing.JTextField();
        cbVigenciaPrin = new javax.swing.JCheckBox();
        btnAceptarPrin = new javax.swing.JButton();
        btnCancelarPrin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcionPrin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPrincipios = new javax.swing.JTable();
        btnNuevoPrin = new javax.swing.JButton();
        btnModificarPrin = new javax.swing.JButton();
        btnSalirPrin = new javax.swing.JButton();

        panDataPrin.setBackground(new java.awt.Color(236, 240, 241));
        panDataPrin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Principio Activo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(44, 62, 80))); // NOI18N

        jLabel1.setText("Nombre:");

        cbVigenciaPrin.setText("Vigente");

        btnAceptarPrin.setText("Aceptar");
        btnAceptarPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPrinActionPerformed(evt);
            }
        });

        btnCancelarPrin.setText("Cancelar");
        btnCancelarPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPrinActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        javax.swing.GroupLayout panDataPrinLayout = new javax.swing.GroupLayout(panDataPrin);
        panDataPrin.setLayout(panDataPrinLayout);
        panDataPrinLayout.setHorizontalGroup(
            panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataPrinLayout.createSequentialGroup()
                .addGroup(panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panDataPrinLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcionPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDataPrinLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDataPrinLayout.createSequentialGroup()
                                .addComponent(btnAceptarPrin)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarPrin))
                            .addComponent(cbVigenciaPrin)
                            .addComponent(txtNombrePrin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panDataPrinLayout.setVerticalGroup(
            panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDataPrinLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombrePrin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcionPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(cbVigenciaPrin)
                .addGap(18, 18, 18)
                .addGroup(panDataPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarPrin)
                    .addComponent(btnCancelarPrin))
                .addGap(31, 31, 31))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Principios Activos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(44, 62, 80))); // NOI18N

        tbPrincipios.setModel(this.principiosModel);
        tbPrincipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPrincipiosseleccionarColumna(evt);
            }
        });
        jScrollPane2.setViewportView(tbPrincipios);

        btnNuevoPrin.setText("Nuevo");
        btnNuevoPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrinActionPerformed(evt);
            }
        });

        btnModificarPrin.setText("Modificar");
        btnModificarPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPrinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNuevoPrin)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPrin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoPrin)
                    .addComponent(btnModificarPrin))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnSalirPrin.setText("Salir");
        btnSalirPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPrinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panDataPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalirPrin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panDataPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalirPrin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPrinActionPerformed
        String nombre = txtNombrePrin.getText();
        String descripcion = txtDescripcionPrin.getText();
        boolean vigencia = (boolean) cbVigenciaPrin.isSelected();
        PrincipioActivo prin = new PrincipioActivo(nombre, descripcion, vigencia);

        if (bandera) {
            PrincipioActivoServicio.crearPrincipioActivo(prin);
        } else {
            prin.setCodigo(principioActivo.getCodigo());
            PrincipioActivoServicio.actualizarPrincipioActivo(prin);
        }
        listarPrincipiosActivos();
        limpiarDatos();
        setPanelEnabled(panDataPrin,false);
    }//GEN-LAST:event_btnAceptarPrinActionPerformed

    private void btnCancelarPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPrinActionPerformed
        setPanelEnabled(panDataPrin,false);
        limpiarDatos();
    }//GEN-LAST:event_btnCancelarPrinActionPerformed

    private void tbPrincipiosseleccionarColumna(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPrincipiosseleccionarColumna
        int codigo = (int) tbPrincipios.getValueAt(tbPrincipios.getSelectedRow(), 0);
        String nombre = tbPrincipios.getValueAt(tbPrincipios.getSelectedRow(), 1).toString();
        String descripcion = tbPrincipios.getValueAt(tbPrincipios.getSelectedRow(), 2).toString();
        boolean vigencia = (boolean) tbPrincipios.getValueAt(tbPrincipios.getSelectedRow(), 3);

        principioActivo = new PrincipioActivo(codigo, nombre, descripcion, vigencia);
    }//GEN-LAST:event_tbPrincipiosseleccionarColumna

    private void btnNuevoPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrinActionPerformed
        bandera = true;
        setPanelEnabled(panDataPrin,true);
        limpiarDatos();

    }//GEN-LAST:event_btnNuevoPrinActionPerformed

    private void btnModificarPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPrinActionPerformed
        if(principioActivo != null){
            bandera = false;
            txtNombrePrin.setText(principioActivo.getNombre());
            txtDescripcionPrin.setText(principioActivo.getDescripcion());
            cbVigenciaPrin.setSelected(principioActivo.isVigente());
            setPanelEnabled(panDataPrin,true);
        }
        else JOptionPane.showMessageDialog(this, "Selecciona un principio activo de la tabla de arriba, por favor.");
    }//GEN-LAST:event_btnModificarPrinActionPerformed

    private void btnSalirPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPrinActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirPrinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPrin;
    private javax.swing.JButton btnCancelarPrin;
    private javax.swing.JButton btnModificarPrin;
    private javax.swing.JButton btnNuevoPrin;
    private javax.swing.JButton btnSalirPrin;
    private javax.swing.JCheckBox cbVigenciaPrin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panDataPrin;
    private javax.swing.JTable tbPrincipios;
    private javax.swing.JTextField txtDescripcionPrin;
    private javax.swing.JTextField txtNombrePrin;
    // End of variables declaration//GEN-END:variables
}
